name: Timeline Bar Regression Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-timeline-bars:
    runs-on: ubuntu-latest

    name: Tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm ci

      - name: Run Timeline Bar Tests
        run: pnpm test:timeline-bars

      - name: Run Full Test Suite
        run: pnpm test -- --run

      - name: Run Linting
        run: pnpm lint

      - name: Test Build
        run: pnpm build
